[project]
name = "python-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.2.0",
    "fastapi>=0.123.5",
    "openai>=2.8.1",
    "pydantic[email]>=2.12.5",
]