[project]
name = "python-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.123.5",
    "openai>=2.8.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]